"""Add created field to Post model

Revision ID: 904741b97428
Revises: 
Create Date: 2025-10-24 03:49:59.054614

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '904741b97428'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('created')

    # ### end Alembic commands ###
